### ISSUE TITLE
Convert weights file to tf file

### ISSUE THREAD

**Issue by smalldroid** [zzh8829/yolov3-tf2#100]
I run convert.py successfully but I only get 4 files same as screenshot, not yolov3.tf. How to solve this problem? Thank you!
![ảnh](https://user-images.githubusercontent.com/237886/68853917-9260ad00-070d-11ea-947c-265c22789d22.png)

**Comment by chandraveshchaudhari** [comment]
i also got yolov3.tf.data-00000-of-00001, yolov3.tf.index, checkpoint file... if your purpose is inference then this repository will work with these file (just assume these file is yolov3.tf). why do you see this as a problem.. tell me. i will try to fix your problem.

**Comment by PieroCV** [comment]
> I run convert.py successfully but I only get 4 files same as screenshot, not yolov3.tf. How to solve this problem? Thank you!
> ![ảnh](https://user-images.githubusercontent.com/237886/68853917-9260ad00-070d-11ea-947c-265c22789d22.png)

Dude, that's the output...
It will work when you call 'yolov3.tf'. Now, if you only want a single file, it's a configuration modification, but it's not a general issue.

**Comment by smalldroid** [comment]
Omg, I tried to changed yolov3.tf.data to yolov3.tf and run detecting with it. I dont know it is true output :D Both of you have same output as me. I thought it a error in convert.py. Thank you!
