### ISSUE TITLE
train.py nan values

### ISSUE THREAD

**Issue by JeffStodd** [zzh8829/yolov3-tf2#103]
> pthon train.py --batch_size 8 --dataset train.tfrecord --val_dataset test.tfrecord --epochs 10 --mode eager_tf --transfer fine_tune --weights yolov3-tiny.tf --tiny

2019-11-18 17:22:38.548319: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-11-18 17:22:42.387889: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-11-18 17:22:43.440550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.733
pciBusID: 0000:01:00.0
2019-11-18 17:22:43.447248: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-18 17:22:43.452289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-18 17:22:43.455984: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-18 17:22:43.463149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.733
pciBusID: 0000:01:00.0
2019-11-18 17:22:43.469160: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-18 17:22:43.473584: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-18 17:22:44.144084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-18 17:22:44.149681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-11-18 17:22:44.153899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-11-18 17:22:44.158184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4708 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-11-18 17:23:00.009183: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:143] Filling up shuffle buffer (this may take a while): 203 of 1024
2019-11-18 17:23:05.496208: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:193] Shuffle buffer filled.
2019-11-18 17:23:05.950491: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-11-18 17:23:06.784628: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
2019-11-18 17:23:07.185721: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
I1118 17:23:08.219413 23336 train.py:135] 1_train_0, nan, [nan, nan]
I1118 17:23:08.446805 23336 train.py:135] 1_train_1, nan, [nan, nan]
I1118 17:23:08.677870 23336 train.py:135] 1_train_2, nan, [nan, nan]
...

Has anyone had this issue and managed to fix it? I labeled my images in Microsoft VoTT, then exported the images to TFRecords. After this I created train and test sets by adding them to their respective tf.data.TFRecordDataset, which are the train.tfrecord and test.tfrecord files.

**Comment by giannimastroscianni** [comment]
Hi. When I started training from scratch with custom dataset, I got a lot of nan as loss values. After some debugging, I saw that I was saving coordinates in a wrong way (y instead of x and viceversa) in tfrecord creation phase. I don't if this could help you

**Comment by JeffStodd** [comment]
> Hi. When I started training from scratch with custom dataset, I got a lot of nan as loss values. After some debugging, I saw that I was saving coordinates in a wrong way (y instead of x and viceversa) in tfrecord creation phase. I don't if this could help you

Thanks for the reply, but I don't think this is likely because VoTT generated the TFRecords. I also manually checked the image in paint with the tfrecord's xmin, xmax, ymin, and ymax values and the bounding boxes were correct for their appropriate image.

**Comment by LongxingTan** [comment]
For me, i don't use all of the code directly from this repo.
But in my case, i found the `box_loss_scale` in yolo_loss need some adjustment. 

```box_loss_scale=2-true_wh[...,0]*true_wh[...,1]/(input_size**2) ```
or, you can also set the learning rate lower

**Comment by JeffStodd** [comment]
> For me, i don't use all of the code directly from this repo.
> But in my case, i found the `box_loss_scale` in yolo_loss need some adjustment.
> 
> `box_loss_scale=2-true_wh[...,0]*true_wh[...,1]/(input_size**2) `
> or, you can also set the learning rate lower

I tried 
> input_size = 1080
> `box_loss_scale=2-true_wh[...,0]*true_wh[...,1]/(input_size**2)
and I still get nans

Then I kept decreasing the learning rate by a factor of 10 but it always results in nan after several steps
For example: 
--learning_rate 0.00001 results in:
I1121 13:26:40.264938  5968 train.py:135] 1_train_0, 17735.833984375, [2718.3704, 15016.129]
I1121 13:26:41.085925  5968 train.py:135] 1_train_1, 17383.044921875, [2659.7124, 14721.998]
I1121 13:26:41.958923  5968 train.py:135] 1_train_2, 17161.466796875, [2625.7314, 14534.401]
I1121 13:26:42.685600  5968 train.py:135] 1_train_3, 16869.408203125, [2600.1125, 14267.961]
I1121 13:26:43.412188  5968 train.py:135] 1_train_4, 16710.314453125, [2556.6914, 14152.289]
I1121 13:26:44.170161  5968 train.py:135] 1_train_5, 16575.455078125, [2562.545, 14011.575]
I1121 13:26:44.795889  5968 train.py:135] 1_train_6, 16601.140625, [2550.871, 14048.936]
I1121 13:26:45.411725  5968 train.py:135] 1_train_7, 16335.5458984375, [2513.4414, 13820.7705]
I1121 13:26:46.043233  5968 train.py:135] 1_train_8, 16442.875, [2531.0208, 13910.52]
I1121 13:26:46.754907  5968 train.py:135] 1_train_9, 16089.982421875, [2479.1753, 13609.473]
I1121 13:26:47.392123  5968 train.py:135] 1_train_10, 16198.5, [2485.1558, 13712.01]
I1121 13:26:48.029229  5968 train.py:135] 1_train_11, 16065.044921875, [2476.1997, 13587.511]
I1121 13:26:48.675010  5968 train.py:135] 1_train_12, 16021.798828125, [2448.3435, 13572.121]
I1121 13:26:49.342316  5968 train.py:135] 1_train_13, 16001.1455078125, [2472.5674, 13527.244]
I1121 13:26:50.124242  5968 train.py:135] 1_train_14, 15734.146484375, [2417.0117, 13315.801]
I1121 13:26:50.850203  5968 train.py:135] 1_train_15, 15661.267578125, [2402.438, 13257.496]
I1121 13:26:51.464170  5968 train.py:135] 1_train_16, nan, [2434.9944, nan]
I1121 13:26:52.100474  5968 train.py:135] 1_train_17, nan, [nan, nan]
I1121 13:26:52.841245  5968 train.py:135] 1_train_18, nan, [nan, nan]
I1121 13:26:53.499819  5968 train.py:135] 1_train_19, nan, [nan, nan]
...

I assume the images and annotations are resized for training automatically? My labelled images are 1080x1080. I'm not sure if this is a problem?

**Comment by NiklasWilson** [comment]
@JeffStodd I don't think that the images are auto resized. As I had similar issues until I manually resized all my images to 416x416.

**Comment by JeffStodd** [comment]
> @JeffStodd I don't think that the images are auto resized. As I had similar issues until I manually resized all my images to 416x416.

How could I resize my images given they are already annotated? Obviously I would have resize the images and then multiply all the x and y detection coords by (416/1080) but I don't know how to modify the tfdataset/tfrecords to do this. At the very least I would have to modify my VoTT project and re-export but I don't think it has this feature.

**Comment by NiklasWilson** [comment]
So the way to do this would be to export your VoTT project as like CSV and than use a script that creates the .tfrecord with the x/y coordinates modified.

Ive seen some examples of this floating around, actually multiple issues posted on this repo have code examples for this. However most of them are talking about how their generated .tfrecords don't work. For example this one
https://github.com/tensorflow/models/blob/master/research/object_detection/dataset_tools/create_pascal_tf_record.py

But I myself ended up just redoing to all my annotations, as it was easier to fix my tiny dataset than trying to get such a script working.

**Comment by PieroCV** [comment]
My solution:
I realised that VoTT export some "corrupt" tfrecord files. So, i coded a little script to identify them.
For a simple situation, verify just with some tfrecords first. If its possible one by one to dataset and val_dataset. If in that verification still got nans, so it's a code situation.

**Comment by Robin2091** [comment]
@PieroCV can you share how you created the script to identify the corrupt tfrecords? I wanna make sure that none of the tfrecords I have are corrupted. Thanks

**Comment by NiklasWilson** [comment]
Maybe that is why my modal doesn't detect anything, all my tfrecords are exports from vott.

**Comment by PieroCV** [comment]
You can call this script from terminal, it has one argument called "path". For example:
`python tfpurge.py --path ./your_folder_with_only_tfrecords`
And needs to be on yolov3_tf2_master folder to be able to works.
Basically, the script trains iterativelly a yolo model for 1 epoch to verify if the batch has a corrupt tfrecord. It uses a kind of binary search, and it takes a relativelly long time.
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
import numpy as np
import cv2
from tensorflow.keras.callbacks import (
    ReduceLROnPlateau,
    EarlyStopping,
    ModelCheckpoint,
    TensorBoard
)
from yolov3_tf2.models import (
    YoloV3, YoloV3Tiny, YoloLoss,
    yolo_anchors, yolo_anchor_masks,
    yolo_tiny_anchors, yolo_tiny_anchor_masks
)
from yolov3_tf2.utils import freeze_all
import yolov3_tf2.dataset as y_dataset

import math
from absl import flags
from absl.flags import FLAGS
import sys
flags.DEFINE_string('path', '.', 'path to tfrecord files')
FLAGS(sys.argv)



size = 416
num_classes = 80
model = YoloV3(size, training=True, classes=num_classes)



def verify(list_tfrecords,model,corrupts=[]):
    is_corrupt = evaluate_tfrecord(list_tfrecords,model)
    if is_corrupt:
        if len(list_tfrecords) == 1:
            print(f'Is corrupt --> {list_tfrecords[0]}')
            corrupts.append(list_tfrecords[0])
        else:
            l1,l2 = split_list(list_tfrecords)
            print(l1[0],'-->',l1[-1],'//',l2[0],'-->',l2[-1])
            corrupts = verify(l1,model,corrupts)
            corrupts = verify(l2,model,corrupts)
    else:
        print(list_tfrecords[0],'-->',list_tfrecords[-1],' not corrupted')
    return corrupts



def split_list(list_to_split):
    index = len(list_to_split)//2 if len(list_to_split)%2==0 else len(list_to_split)//2 + 1
    return list_to_split[:index],list_to_split[index:]


def evaluate_tfrecord(path,model):
    pre_weights = './checkpoints/yolov3.tf'
    path_classes = './hat.names'
    size = 416
    epochs = 1
    num_classes = 80
    batch_size = 8
    anchors = yolo_anchors
    anchor_masks = yolo_anchor_masks
    learning_rate = 1e-3
    
    train_dataset = y_dataset.load_tfrecord_dataset(path, path_classes)
    train_dataset = train_dataset.shuffle(buffer_size=1024)  # TODO: not 1024
    train_dataset = train_dataset.batch(batch_size)
    train_dataset = train_dataset.map(lambda x, y: (
        y_dataset.transform_images(x,size),
        y_dataset.transform_targets(y, anchors, anchor_masks, num_classes)))
    train_dataset = train_dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    
    test_dataset = y_dataset.load_tfrecord_dataset(path, path_classes)
    test_dataset = test_dataset.batch(batch_size)
    test_dataset = test_dataset.map(lambda x, y: (
        y_dataset.transform_images(x, size),
        y_dataset.transform_targets(y, anchors, anchor_masks, num_classes)))
    optimizer = tf.keras.optimizers.Adam(lr=learning_rate)
    loss = [YoloLoss(anchors[mask], classes=num_classes,ignore_thresh=0.1)
            for mask in anchor_masks]
    model=define_model('fine_tune','./checkpoints/yolov3.tf',model,num_classes)
    model.compile(optimizer=optimizer, loss=loss)
    history = model.fit(train_dataset,
                    epochs=epochs,
                    validation_data=test_dataset,
                    verbose = 0
                   )
    result = math.isnan(history.history['loss'][-1])
    return result



def define_model(transfer,path_weights,model,num_classes):
    if transfer == 'none':
        return
    elif transfer == 'fine_tune':
        model.load_weights(path_weights)
        darknet = model.get_layer('yolo_darknet')
        freeze_all(darknet)
    elif transfer == 'frozen':
        model.load_weights(path_weights)
        freeze_all(model)
    elif transfer == 'darknet':
        model.load_weights(path_weights)
        init_model = YoloV3(size, training=True, classes=num_classes)
        for l in model.layers:
            if l.name != 'yolo_darknet' and l.name.startswith('yolo_'):
                l.set_weights(init_model.get_layer(
                    l.name).get_weights())
            else:
                freeze_all(l)
    elif transfer == 'no_output':
        model.load_weights(path_weights)
        init_model = YoloV3(size, training=True, classes=num_classes)
        for l in model.layers:
            if l.name.startswith('yolo_output'):
                l.set_weights(init_model.get_layer(
                    l.name).get_weights())
            else:
                freeze_all(l)
    elif transfer == 'only_darknet':
        model_pretrained = YoloV3(size, training=True, classes=80)
        model_pretrained.load_weights('./checkpoints/yolov3.tf')
        model.get_layer('yolo_darknet').set_weights(model_pretrained.get_layer('yolo_darknet').get_weights())
        darknet = model.get_layer('yolo_darknet')
        freeze_all(darknet)
    elif transfer == 'load_weights':
        model.load_weights(path_weights)
    else:
        raise Exception('Transfer: fine_tune,frozen,darknet,no_output,only_darknet,none')
        return None
    return model



def get_list_dataset(path):
    return [path+'/'+s  for s in os.listdir(path)]



dataset = get_list_dataset(FLAGS.path)
corrupts = verify(dataset,model)
print('Corrupts: ',corrupts)
```

**Comment by PieroCV** [comment]
> Maybe that is why my modal doesn't detect anything, all my tfrecords are exports from vott.
Check the tfrecord files. Or Did you change something on models.py?

**Comment by NiklasWilson** [comment]
It might be easier to check the record using the "parse_single_example" function in dataset.py. Depending on what exactly where looking for to figure out if it is corrupt.
Is it really the tfrecord? or is it the image connected to the record?

**Comment by akkaze** [comment]
Have you fixed this bug？I got the same bug trained on voc2007 from scratch

**Comment by Robin2091** [comment]
@PieroCV Hi, thanks so much for the script. I am using yolov3tiny to train and i noticed that your script uses yolov3. I also think it can run a lot faster if tiny is used. Can you guide me with what changes I have to make to get it to work with tiny. I tried changing all the model names to tiny but i get an error about the loss. I got the script working just with yolov3

**Comment by PieroCV** [comment]
@NiklasWilson It's a good idea. I was looking for issues on tfrecords decoded and the image per se, but i didn't found anything wrong. That's why I opted for this solution.
@akkaze I did, i don't really know if this is your solution, but you won't lose anything trying.

**Comment by PieroCV** [comment]
@Robin2091 
Uhmmm i would have to check it... I use only Yolov3 so I usually skip all code related to yolov3Tiny...
But, if you wanna try, need to check the Model instance and the Loss instance (I guess xD).

**Comment by AnaRhisT94** [comment]
@JeffStodd  @NiklasWilson @PieroCV  @Robin2091 
The loss is `nan` when the annotations are wrong, Darknet's annotations are `x_center, y_center, width, height` and in this repo the annotations are different: `xmin, ymin, xmax, y_max`. Try first training on one image with one annotation, get that to work, and then you'll succeed with more than 1 image. good luck. (There's already a code ready to check with one picture in this repo) the idea is to get it work with the correct annotations, then you can generalize it to create .tfrecord with a couple of images, see that it works, then createt a big .tfrecord and continue like that.

**Comment by PieroCV** [comment]
> @JeffStodd @NiklasWilson @PieroCV @Robin2091
> The loss is `nan` when the annotations are wrong, Darknet's annotations are `x_center, y_center, width, height` and in this repo the annotations are different: `xmin, ymin, xmax, y_max`. Try first training on one image with one annotation, get that to work, and then you'll succeed with more than 1 image. good luck. (There's already a code ready to check with one picture in this repo) the idea is to get it work with the correct annotations, then you can generalize it to create .tfrecord with a couple of images, see that it works, then createt a big .tfrecord and continue like that.

That's just what I did with the big code up there...
Totaly agree with you.

**Comment by Robin2091** [comment]
@AnaRhisT94 Hi, I created a script that checks for "corrupted" tfrecord files and I removed them from my dataset. I don't get NAN loss values anymore. However, I still have the annotations as xmin, ymin, xmax, ymax. I haven't tried training on my whole dataset yet. Will the format I currently have give me incorrect results for training? 

I also ran training with 5 epochs on 20 examples as a test. I trained with pre-trained weights loaded and was able to get detections(accuracy was very low obviously). Does this mean everything is working fine? 

Thank you for the advice.

**Comment by AnaRhisT94** [comment]
> @AnaRhisT94 Hi, I created a script that checks for "corrupted" tfrecord files and I removed them from my dataset. I don't get NAN loss values anymore. However, I have the annotations as xmin, ymin, xmax, ymax(since I imported from Vott). I haven't tried training on my whole dataset yet. Will the format I currently have give me incorrect results for training?
> 
> I also ran training with 5 epochs on 20 examples as a test. I trained with pre-trained weights loaded and was able to get detections(accuracy was very low obviously). Does this mean everything is working fine?
> 
> Thank you for the advice.

Yeah.
Check the score threshold in detect.py and lower that value.
The loss should be lower than 6 for good detections.

**Comment by Robin2091** [comment]
@AnaRhisT94 Ok, I will make sure to lower the threshold when I actually train with all of my dataset. Just for clarification, I don't have to change the annotations? And if I am able to run detect.py and get detections everything is working fine?

Thanks for your patience.

**Comment by AnaRhisT94** [comment]
> @AnaRhisT94 Ok, I will make sure to lower the threshold when I actually train with all of my dataset. Just for clarification, I don't have to change the annotations? And if I am able to run detect.py and get detections everything is working fine?
> 
> Thanks for your patience.

Yup.
Tag me whenever you want.
Im not going anywhere anytime soon (:

**Comment by Robin2091** [comment]
@AnaRhisT94 Hi, I have another question, do you know if using binary cross entropy loss function causes any drastic changes to training. I originally changed the loss function to binary cross entropy because I am training with 1 class. When i changed it back to sparse_categorical_crossentropy (i wanted to see what will happen) everything was going fine until i got an error saying that a label of -1 was received which was out of range (0,1]. I'm assuming its something with a tfrecord file being "corrupted" just as with the nans. But I just want to confirm if there are any negative effects of using binary crossentropy since this error doesn't show up when I use that as the loss function.

Thank you.

**Comment by AnaRhisT94** [comment]
> @AnaRhisT94 Hi, I have another question, do you know if using binary cross entropy loss function causes any drastic changes to training. I originally changed the loss function to binary cross entropy because I am training with 1 class. When i changed it back to sparse_categorical_crossentropy (i wanted to see what will happen) everything was going fine until i got an error saying that a label of -1 was received which was out of range (0,1]. I'm assuming its something with a tfrecord file being "corrupted" just as with the nans. But I just want to confirm if there are any negative effects of using binary crossentropy since this error doesn't show up when I use that as the loss function.
> 
> Thank you.

I don't think you need to change the loss function. Use the same function. Try with 1-10 images with 10 annotation of that object, train on it and try to detect. (also be pragmatic and break it to simple cases and make it work on simple case first - then it'll probably generalize to more images).

About the `-1` value. In my `.tfrecord` creation script I'm checking whether the value is in this range. IF it's not,  I won't add it to the `.tfrecord`, I also allow for small error , if it's `1.0-1.1` or `-0.1~0` I clip it to `1` or `0`. this clipping is helpful when you're doing affine transformations like `translate` and the `bboxes` may move a little bit of the image resolution, but you don't have to do that if you don't want to and just dismissed values that aren't in the `0-1` range.

**Comment by Robin2091** [comment]
@AnaRhisT94 I tried your method, I removed the extra corrupted files that were caused by the sparse_categorical_crossentropy loss function. The training is working fine and I have no NANs and no errors. Thank you! 

Just another quick question, do you know how to get the total accuracy of the model? When I have metrics = "accuracy" in the compile line of the model, I get 2 different accuracy readings for the train and validation dataset: yolo_0_accuracy and yolo_1_accuracy.

**Comment by zzh8829** [comment]
Please refer to this tutorial https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md on custom training. I also introduce a dataset visualization tool to help debugging custom dataset issue. If you have further problem please open new tickets
