### ISSUE TITLE
BaseCollectiveExecuter::StartAbort Out of range: End of Sequence

### ISSUE THREAD

**Issue by muhammad-maaz-confiz** [zzh8829/yolov3-tf2#104]
![TF2 0TinyYolo_Training](https://user-images.githubusercontent.com/40428956/69243232-7608b880-0bc4-11ea-93b6-349b397ce7cd.png)

Hi,

While training Tiny Yolo on VOC dataset, in the end of each epoch I am getting the error "BaseCollectiveExecuter::StartAbort Out of range: End of Sequence". Also training early stops after 4 epochs. The terminal outputs are attached. Note that I am using ubuntu 18.04 with TF2.0.

Also while using eager mode training, all went right.
![training_tf2 0](https://user-images.githubusercontent.com/40428956/69244672-2d063380-0bc7-11ea-9a45-71bf18c18284.png)

**Comment by AnaRhisT94** [comment]
I think it's logical to add the `repeat()` function while creating your training and validation dataset.

**Comment by muhammad-maaz-confiz** [comment]
Hi @AnaRhisT94,

So while loading TFRecords, using dataset.map(....).repeat() will resolve this issue? Please guide thoroughly as I am new to Tensorflow and wanted to investigate in depth details. 

Thanks

**Comment by AnaRhisT94** [comment]
> Hi @AnaRhisT94,
> 
> So while loading TFRecords, using dataset.map(....).repeat() will resolve this issue? Please guide thoroughly as I am new to Tensorflow and wanted to investigate in depth details.
> 
> Thanks

Best thing it to try and see. Should work though :)

**Comment by NiklasWilson** [comment]
Another option is switching from "fit" to "eager_tf".

**Comment by NiklasWilson** [comment]
@AnaRhisT94 Did adding the .repeat() resolve this for you? and have you been able to train a modal that did detects something (even inaccuratly)?

**Comment by muhammad-maaz-confiz** [comment]
Hi @NiklasWilson ,

adding .repeat() and passing steps_per_epoch in model.fit() solves the issue for me. Because of the busy routine I did not able to test the model. will let you know about detection once I test the model.

**Comment by NiklasWilson** [comment]
@muhammad-maaz-confiz Awesome! I will add that to my code tonight and test myself too. While eagerly awaiting the results of tests :)

**Comment by NiklasWilson** [comment]
Side note this "early stops after 4 epochs" can happen with or without this error. It is related to this line of code.
`            ReduceLROnPlateau(verbose=1),
            EarlyStopping(patience=3, verbose=1),`

You can modify the patience value to decrease the premature stopping.
I have change mine to
`  ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=3, verbose=1)
    EarlyStopping(monitor='val_loss', min_delta=0, patience=10, verbose=1)`

**Comment by muhammad-maaz-confiz** [comment]
Thanks @NiklasWilson and @AnaRhisT94 ,

While repeating the dataset and adding steps_per_epoch in model.fit() seems to resolve the issue for initial epochs and the issue reappeared after a couple of epochs (3 epochs for me). What could be gone wrong? Also note that the training automatically stops after 9 epochs and no message regarding early stopping. Thanks
![Tf20_End_fSequence](https://user-images.githubusercontent.com/40428956/69474335-b5602080-0de1-11ea-81bf-2121b780858a.png)

**Comment by NiklasWilson** [comment]
@muhammad-maaz-confiz 
This problem went away for me when I put the repeat here
`    train_dataset = train_dataset.map(lambda x, y: (
        dataset.transform_images(x, FLAGS.size),
        dataset.transform_targets(y, anchors, anchor_masks, 80))).repeat()`

**Comment by mmaaz60** [comment]
By repeating the training dataset and specifying steps_per_epoch and validation_steps in model.fit(), I am able to get rid of this error/warning.

**Comment by zzh8829** [comment]
I believe this error doesn't actually affect training, it's likely a bug from tensorflow
