### ISSUE TITLE
Multi Scale Training

### ISSUE THREAD

**Issue by mmaaz60** [zzh8829/yolov3-tf2#112]
Does this repo support multi scale training as is used to be in darknet and mentioned in Yolov3 paper?

**Comment by AnaRhisT94** [comment]
> Does this repo support multi scale training as is used to be in darknet and mentioned in Yolov3 paper?

You don't need multi-scale training in YoloV3, it's already have it built-in.

**Comment by zzh8829** [comment]
AnaRhisT94 is correct. Here is a quick visualization of yolov3 architecture
```
input ---> darknet -> conv ---> conv ---> conv
                        |        |          |
                      out_1     out_2     out_3
```

Each conv layer basically introduce a new *scale* and produce an output at that scale.
Yolov3 basically has 3-scale training and detection baked into the network architecture
Training with one image is in fact training three outputs at the same time
