### ISSUE TITLE
Could u plz tell me why you do not divide 'grid' after the exp()*anchors ?

### ISSUE THREAD

**Issue by zhaotf16** [zzh8829/yolov3-tf2#118]
https://github.com/zzh8829/yolov3-tf2/blob/53e6d7675fc2790248a1d23ce6ff2aa3195f0b98/yolov3_tf2/models.py#L166

**Comment by zzh8829** [comment]
because box_wh is the width and height of bounding box which is independent from grid.
box_xy is the coordinate of the box which takes grid into account as you can see the in line before
