### ISSUE TITLE
  export_tfserving.py    KeyError: 'yolo_nms_1'

### ISSUE THREAD

**Issue by chenying99** [zzh8829/yolov3-tf2#121]
运行命令：python export_tfserving.py --output serving/yolov3/1/ 

2019-12-10 18:43:26.760068: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
I1210 18:43:32.300182 1067564 export_tfserving.py:55] weights loaded
2019-12-10 18:43:50.461863: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1781: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_va
riable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1210 18:44:07.253870 1067564 deprecation.py:506] From E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1781: calling BaseResourceVariable.__init__ (from te
nsorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: serving/yolov3/1/assets
I1210 18:44:12.895049 1067564 builder_impl.py:771] Assets written to: serving/yolov3/1/assets
I1210 18:44:15.132097 1067564 export_tfserving.py:58] model saved to: serving/yolov3/1/
I1210 18:44:28.737789 1067564 export_tfserving.py:62] {'yolo_nms_3_3': TensorSpec(shape=(None,), dtype=tf.int32, name='yolo_nms_3_3'), 'yolo_nms_1_1': TensorSpec(shape=(None, 100), dtype=tf.float32, name='y
olo_nms_1_1'), 'yolo_nms_2_2': TensorSpec(shape=(None, 100), dtype=tf.float32, name='yolo_nms_2_2'), 'yolo_nms_0': TensorSpec(shape=(None, 100, 4), dtype=tf.float32, name='yolo_nms_0')}
I1210 18:44:28.741778 1067564 export_tfserving.py:65] classes loaded
Traceback (most recent call last):
  File "export_tfserving.py", line 87, in <module>
    app.run(main)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_tfserving.py", line 74, in main
    "yolo_nms_1"], outputs["yolo_nms_2"], outputs["yolo_nms_3"]
KeyError: 'yolo_nms_1'

**Comment by iosipeld** [comment]
Hi, 

I had the same problem, you need to modify the line in file `export_tfserving.py` to look like this: `boxes, scores, classes, nums = outputs["yolo_nms_0"], outputs["yolo_nms_1_1"], outputs["yolo_nms_2_2"], outputs["yolo_nms_3_3"]`

**Comment by chenying99** [comment]
I have modify the file export_tfserving.py according you opinions,that's ok  thank you
