### ISSUE TITLE
"load_darknet_weights" function error

### ISSUE THREAD

**Issue by cspk79** [zzh8829/yolov3-tf2#122]
Hi, I am trying to convert yolov3.weights to yolov3.tf using convert.py.
Unfortunately, I got two error messages inside the load_darknet_weights function of utils.py.

<Error Message 1> 
    File "c:\Users\my\Desktop\workT\yolov3-tf2\convert.py", line 21, in main
    load_darknet_weights(yolo, FLAGS.weights, FLAGS.tiny)
  File "c:\Users\my\Desktop\workT\yolov3-tf2\yolov3_tf2\utils.py", line 49, in load_darknet_weights
    in_dim = layer.input_shape[-1]
  File "C:\Users\my\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 1604, in input_shape
    ' has multiple inbound nodes, '
AttributeError: The layer "conv2d has multiple inbound nodes, with different input shapes. Hence the notion of "input shape" is ill-defined for the layer. Use `get_input_shape_at(node_index)` instead.

<Error Message 2>   
File "c:\Users\my\Desktop\workT\yolov3-tf2\yolov3_tf2\utils.py", line 65, in load_darknet_weights
    conv_weights = np.fromfile(wf, dtype=np.float32, count=np.product(conv_shape))
TypeError: 'tuple' object cannot be interpreted as an integer

Anyone meet these errors before?
Please help me solve this problems.

**Comment by edurenye** [comment]
Why was that closed? I got the same error

**Comment by edurenye** [comment]
This happens to me when I add size to create the model:
`yolo = YoloV3Tiny(size=FLAGS.size, classes=FLAGS.num_classes)`

In convert for example it you change line:
`yolo = YoloV3Tiny(classes=FLAGS.num_classes)`
 for the previous one, I get the error.

And #269 fixes the error.

**Comment by cspk79** [comment]
Now I don't remember exactly because it's been a long time.
I guess I made a simple mistake in the configuration at that time.
So I closed this issue.
