### ISSUE TITLE
How to obtain multiple confidences for each bbox?

### ISSUE THREAD

**Issue by yu-takagi** [zzh8829/yolov3-tf2#13]
Thanks for great work!
Can I obtain multiple (e.g., top-10) outputs for each bboxt? 
Current implementation returns only the class with the highest probability (e.g., dog 0.8 coordinates), but I wonder if I can obtain the results like:
dog 0.8 coordinatesA
cat 0.1 coordinatesA
dog 0.5 coordinatesB
cat 0.3 coordinatesB
horse 0.1 coordinatesB
...

**Comment by zzh8829** [comment]
the single bounding box is part of the non max suppression algorithm in yolo_nms function.
If you really want multiple score per box you can make the model output boxes_0, boxes_1, boxes_2 directly.
