### ISSUE TITLE
ModuleNotFoundError: No module named 'yolov3_tf2'

### ISSUE THREAD

**Issue by chirjot** [zzh8829/yolov3-tf2#131]
**C:\\\\WorkingDirectory>** python convert.py
Traceback (most recent call last):
  File "detect.py", line 7, in <module>
    from yolov3_tf2.models import (
ModuleNotFoundError: No module named 'yolov3_tf2'
**C:\\\\WorkingDirectory>** python -c 'import tensorflow as tf; print(tf.__version__)'
2.0.0

**Comment by ahmadasghar1992** [comment]
When I write the command python tools/visualize_dataset.py --classes=./data/voc2012.names
to visualize my data it throws a module not found an error with ModuleNotFoundError: No module named 'yolov3_tf2'. In visualize_dataset.py I can see that the yolov3_tf2 is not resolving. On the other hand, the inference is completely working fine. 

Am I doing something wrong? I am new to this stuff, requesting help.

**Comment by Leon-S-Kenndy** [comment]
have you fixed it? I met the same problem

**Comment by SEASKY-Master** [comment]
have you fixed it? I met the same problem

**Comment by ali1366** [comment]
I had the same problem.
The problem resolved  when added `import sys
sys.path.append('./')` to the top of tools/visualize_dataset.py file.
