### ISSUE TITLE
how do use transfer learning for custom class. (Unresolved object in checkpoint) 

### ISSUE THREAD

**Issue by miladfa7** [zzh8829/yolov3-tf2#134]
I'm trying to train my own dataset with darknet weights but  I get is this error message

> python3 train.py --dataset ./train.tfrecord --classes ./data/coco.names --num_classes 2 --mode fit --transfer darknet --batch_size 16 --epochs 10 --weights ./checkpoints/yolov3-tiny.tf --tiny

`ValueError: Shapes (21,) and (255,) are incompatible`
`W1226 20:38:51.236896 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-6`
`W1226 20:38:51.237092 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-7`
`W1226 20:38:51.237151 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-8`
`W1226 20:38:51.237223 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-6.arguments`
`W1226 20:38:51.237268 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-6._variable_dict`
`W1226 20:38:51.237330 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-6._trainable_weights`
`W1226 20:38:51.237375 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-6._non_trainable_weights`
`W1226 20:38:51.237443 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-7.arguments`
`W1226 20:38:51.237489 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-7._variable_dict`
`W1226 20:38:51.237555 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-7._trainable_weights`
`W1226 20:38:51.237600 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-7._non_trainable_weights`
`W1226 20:38:51.237646 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-8.arguments`
`W1226 20:38:51.237691 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-8._variable_dict`
`W1226 20:38:51.237735 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-8._trainable_weights`
`W1226 20:38:51.237780 140136449599296 util.py:144] Unresolved object in checkpoint: (root).layer-8._non_trainable_weights`
**W1226 20:38:51.237830 140136449599296 util.py:152] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit.**
 `See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.`

**Comment by zzh8829** [comment]
you need to set the flag --weights_num_class for transfer learning with different number of classes 

See this tutorial for details https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md

**Comment by bgamini** [comment]
I set --weights_num_classes 80 but it still doesn't works.
