### ISSUE TITLE
 I met an error

### ISSUE THREAD

**Issue by c987617162** [zzh8829/yolov3-tf2#136]
Hello there
I encountered an error
When I was training the second epochs
Graphics card GTX1050TI
RAM 16G
![Snipaste_2019-12-29_22-41-56.png](https://i.loli.net/2019/12/29/QzGbf1OvLU8ownM.png)

**Comment by zzh8829** [comment]
Hi this is due to the number of bounding boxes per image exceeded the `100` preset. Please set the `--yolo_max_boxes` flag to 200 and then try again

**Comment by c987617162** [comment]
It worked, thank you!!
