### ISSUE TITLE
True box?

### ISSUE THREAD

**Issue by paapu88** [zzh8829/yolov3-tf2#151]
Dear All,

It seems that a single ground truth (y_true) is associated only the one of the three grids, the other two remaining empty. Is this a feature or a bug (or did I get it wrong...)?

How should I modify the code to get the y_true in all three grids?

Terveisin, Markus

**Comment by zzh8829** [comment]
I am not 100% clear on what you are asking. A single bounding box is only associate with one anchor with highest IOU. So if you have one label, only 1 out of the 3 grid would have data in it. Each of the 3 grid contains label for 3 different anchors.

**Comment by paapu88** [comment]
Yes, you got it right. In some other implementations I have seen of yolo, the same true box value is given for all the three grids during the training. But I have no idea which approach is better.

**Comment by zzh8829** [comment]
I am not sure either but the yolov3 author's darknet repo does one grid only.
