### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by LordTrololo** [zzh8829/yolov3-tf2#209]
Hi,
so I have a question. 

Lets say I want to train the model to recognize a chair. I have a dataset of 400 images of chairs. 

I can train the model on these images, but the thing is - the boundig box of the chair is the entire image. It is not as if I have 400 Images with chairs in them but I have 400 images with **exclusively** chairs in them, nothing else is visible and the bounding box of the chair is the entire image.

My question is - is this training Dataset detrimental to the model ?

**Comment by zzh8829** [comment]
i believe it would be able to recognize chair with your dataset as is. i would recommend augmenting your dataset with more versatile background environment, even just embed it onto random background would help alot

**Comment by LordTrololo** [comment]
Hi, thanx for answer.

I made a few tests and as it seems - if I only have **exclusively** chairs objects in my training dataset than the Yolo model doesnt work.

When I train the model with something else (where I have dataset which is not only bounding boxes of the objects in question) then everything works as expected.

So it seems that in order to learn the model needs both the boundig boxes and some form of 
background around/behind it.

And as you suggested I am already making an augmented dataset to try to solve my specific chairs problem.

**Comment by LordTrololo** [comment]
I now tested the model by using images of my chairs appended (and annotated) in larger images (so some other background is present beside a chair). When chairs are only a (smaller) part of an image and not the entire image per se - then the algorithm seems to be working ok.

So I will close this and the bottom line is - you cannot train the model by having hundred images of your class object (in my case chairs) and nothing else in the images. 
However when your objects are present in the hundred images and you properly annotate the bounding box of them - then everything works ok.
