### ISSUE TITLE
Magic numbers and model summary

### ISSUE THREAD

**Issue by emadboctorx** [zzh8829/yolov3-tf2#222]
I'm having hard time with reading your code specially the parts with magic numbers for example:
Line 145 yolov3_tf2.models:

        x = Lambda(lambda x: tf.reshape(x, (-1, tf.shape(x)[1], tf.shape(x)[2],
                                            anchors, classes + 5)))(x)
why classes + 5 and not maybe classes or classes + 1?

And of course I can name many others, would you please add some comments explaining what these numbers represent?

Another concern: model summary does not show output shapes, it's full of None, None, None, (not entirely, there are occasional 13 x 13 x 256 and a few other shapes) whenever I start the training on the example dataset you included in the documentation, everything is working as expected, the loss is decreasing gradually, saving sometimes taking more than usual but it's okay however when I check the output shapes in the summary before training, I'm expecting it should match or at least be close to https://gist.github.com/fabito/a49bb6a5593594f26275bc90baba6e32 however I get very different results, How am I supposed to ensure this is even a correct feature map?

Here is what you get by 

    mod = YoloV3(size=416)
    mod.summary()

<img width="717" alt="Screen Shot 2020-04-01 at 5 49 37 PM" src="https://user-images.githubusercontent.com/58062537/78158104-afb0c200-73f5-11ea-8faa-e2c1c58dc4f6.png">
<img width="750" alt="Screen Shot 2020-04-01 at 5 50 03 PM" src="https://user-images.githubusercontent.com/58062537/78158167-bf300b00-73f5-11ea-8e57-4406c830ed0a.png">

**Comment by asquare92** [comment]
`classes+5` is this size of the output vector for one anchor box. For example if you have three classes the output vector (considering just one anchor box, there are a total of three anchors for each grid cell) would be [total_num_classes(1=correct_class, 0=incorrect class), Objectness Score, bx, by, bw, by] i.e [1,0,0,0.9,0.1,0.2,0.3,0.4]. These are just random numbers.
