### ISSUE TITLE
 I have only two classes now, more than 4,000 images, and can not use pre-training, the model is very poor, do you have any good suggestions?

### ISSUE THREAD

**Issue by guangmingdexin** [zzh8829/yolov3-tf2#236]
I have only two classes now, more than 4,000 images, and can not use pre-training, the model is very poor, do you have any good suggestions?

**Comment by tsk15535904190** [comment]
you should use pre_training,I training one class and 320 pictures ,with pre-training ,it's works

**Comment by guangmingdexin** [comment]
I also want to use pre-training, but the competition requires us not to use

**Comment by zzh8829** [comment]
pretraining is almost required for good results, you could try doing dataset augmentation using framework like `imgaug`
