### ISSUE TITLE
Run in eager mode

### ISSUE THREAD

**Issue by AlonLahav** [zzh8829/yolov3-tf2#24]
I was trying to run `detect.py` eagerly, but when setting a breakpoint it never stops (used PyCharm).
For example, I tried to set up a breakpoint at the beginning of `YoloV3` function. It stops at the definition call:
```
    if FLAGS.tiny:
        yolo = YoloV3Tiny()
    else:
        yolo = YoloV3()
```
But do not stops at prediction call:
```
boxes, scores, classes, nums = yolo(img)
```
Probably I miss something here..

**Comment by zzh8829** [comment]
it worked for me before, did you try setting breakpoints inside of yolo models.
