### ISSUE TITLE
tf.pad not working correctly 

### ISSUE THREAD

**Issue by waiiinta** [zzh8829/yolov3-tf2#25]
I have found that [tf.pad](https://github.com/zzh8829/yolov3-tf2/blob/master/yolov3_tf2/dataset.py#L115) in dataset.py return the same shape as before (None,5).

**Comment by waiiinta** [comment]
Not sure, the shape that you wanted is (100,5) or not but I change the code to 

```
if y_train.shape[0] == None:
      y_train = tf.reshape(y_train,[1,y_train.shape[1]])
      padding_len = 100-y_train.shape[0]
    else:
      padding_len = 100-y_train.shape[0]

paddings = tf.constant([[0,padding_len], [0, 0 ]])
y_train_pad = tf.compat.v2.pad(y_train, paddings, 'CONSTANT', constant_values=0)
return x_train, y_train_pad
```
the shape of y_train_pad will be (100,5)

**Comment by zzh8829** [comment]
`None` dimension is determined at run time, I believe its simply a placeholder value.
tensor.shape[0] only works in eager mode, it won't work if u try to compile this to tf graph
