### ISSUE TITLE
训练中的问题

### ISSUE THREAD

**Issue by weidaoquan** [zzh8829/yolov3-tf2#251]
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  {{function_node __inference_Dataset_map_<lambda>_13967}} Paddings must be non-negative: 0 -52
         [[{{node Pad}}]]
         [[IteratorGetNext]]
  (1) Invalid argument:  {{function_node __inference_Dataset_map_<lambda>_13967}} Paddings must be non-negative: 0 -52
         [[{{node Pad}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_2]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_49666]

Function call stack:
distributed_function -> distributed_function

**Comment by funkydude755** [comment]
i solved this by removing the smallest bounding boxes from my data-set
