### ISSUE TITLE
Error when split the dataset

### ISSUE THREAD

**Issue by axiaobugs** [zzh8829/yolov3-tf2#252]
when use the
python3 tools/voc2012.py \
  --data_dir './data/voc2012_raw/VOCdevkit/VOC2012' \
  --split train \
  --output_file ./data/voc2012_train.tfrecord
and show the error
File "tools/voc2012.py", line 99, in main
    name, _ = image.split()
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by axiaobugs** [comment]
same as running in the colabs 

Traceback (most recent call last):
  File "tools/voc2012.py", line 111, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tools/voc2012.py", line 99, in main
    name, _ = image.split()
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wsypy** [comment]
在代码的第96行：FLAGS.data_dir, 'ImageSets', 'Main', '%s.txt' % FLAGS.split)).read().splitlines()。当你在运行代码时python tools/voc2012.py \
  --data_dir './data/voc2012_raw/VOCdevkit/VOC2012' \
  --split train \
他只读取了名称为train.txt的文件，所以会出现这样的错误。

我想问的是你解决这里的问题了吗？怎样读取所有的xx_train.txt文件

**Comment by baihei-1122** [comment]
At first I chang the 'aeroplane_%s.txt%s.txt' into '%s.txt',the same question I have, but when I change into orignal like 'aeroplane_%s.txt', the problem is solved.The reason why it can be useful, I don't know,maybe you can ask for the author.

> 在代码的第96行：FLAGS.data_dir, 'ImageSets', 'Main', '%s.txt' % FLAGS.split)).read().splitlines()。当你在运行代码时python tools/voc2012.py 
> --data_dir './data/voc2012_raw/VOCdevkit/VOC2012' 
> --split train 
> 他只读取了名称为train.txt的文件，所以会出现这样的错误。
> 我想问的是你解决这里的问题了吗？怎样读取所有的xx_train.txt文件

**Comment by wsypy** [comment]
> 起初，我将'aeroplane_％s.txt％s.txt'更改为'％s.txt'，这是我遇到的相同问题，但是当我像'aeroplane_％s.txt'一样改成原始格式时，问题就解决了。它之所以有用的原因，我不知道，也许您可​​以要求作者。
> 
> > 在代码的第96行：FLAGS.data_dir，“ ImageSets”，“ Main”，“％s.txt”％FLAGS.split））。read（）。splitlines（）。当您在运行代码时python tools / voc2012 .py 
> > --data_dir'./data/voc2012_raw/VOCdevkit/VOC2012'-- 
> > split train 
> > 他只读取了名称为train.txt的文件，所以会出现这样的错误。
> > 我想问的是你解决这里的问题了吗？怎样重新所有的xx_train.txt文件

谢谢，我貌似知道了问题所在。我查看了tensorflow官方声称tfrecord的代码，他们在读取xx_train.txt文件时，代码前加了aeroplane_，所以在运行此代码时我们也加上aeroplane_。如果不加aeroplane_，那么我们读取的将是train.txt。最终加上aeroplane_后我们将读取aeroplane_train.txt，生成tfrecord就可以训练。

之前我对于voc数据集理解错了，我之前以为classname_train.txt只包含classname这一类物体的，其实不是。xxx_train.txt中和yyy_train中图片是一样的，包含所有用于train的图片，相应的后面的-1表示某一图片中不含xxx类这一物体，1表示包含xxx，0表示比较难以分辨xxx。这也就是我们可以在前面加上aeroplane_，当然我们也可以写成20类物体的任意一个名称，如person_,car_，等等。

不知道你是否能读懂中文

**Comment by baihei-1122** [comment]
好的，我也理解了，谢谢！
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wsypy"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 晚上9:09
收件人: "zzh8829/yolov3-tf2"<yolov3-tf2@noreply.github.com&gt;; 
抄送: "704837900"<704837900@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zzh8829/yolov3-tf2] Error when split the dataset (#252)





  
起初，我将'aeroplane_％s.txt％s.txt'更改为'％s.txt'，这是我遇到的相同问题，但是当我像'aeroplane_％s.txt'一样改成原始格式时，问题就解决了。它之所以有用的原因，我不知道，也许您可​​以要求作者。
  
在代码的第96行：FLAGS.data_dir，“ ImageSets”，“ Main”，“％s.txt”％FLAGS.split））。read（）。splitlines（）。当您在运行代码时python tools / voc2012 .py
 --data_dir'./data/voc2012_raw/VOCdevkit/VOC2012'--
 split train
 他只读取了名称为train.txt的文件，所以会出现这样的错误。
 我想问的是你解决这里的问题了吗？怎样重新所有的xx_train.txt文件
   
谢谢，我貌似知道了问题所在。我查看了tensorflow官方声称tfrecord的代码，他们在读取xx_train.txt文件时，代码前加了aeroplane_，所以在运行此代码时我们也加上aeroplane_。如果不加aeroplane_，那么我们读取的将是train.txt。最终加上aeroplane_后我们将读取aeroplane_train.txt，生成tfrecord就可以训练。
 
之前我对于voc数据集理解错了，我之前以为classname_train.txt只包含classname这一类物体的，其实不是。xxx_train.txt中和yyy_train中图片是一样的，包含所有用于train的图片，相应的后面的-1表示某一图片中不含xxx类这一物体，1表示包含xxx，0表示比较难以分辨xxx。这也就是我们可以在前面加上aeroplane_，当然我们也可以写成20类物体的任意一个名称，如person_,car_，等等。
 
不知道你是否能读懂中文

**Comment by axiaobugs** [comment]
thanks

**Comment by saadwazir** [comment]
open tools/voc2012.py
change line no 19 to
name= image
-------------

this works for me :)

**Comment by zzh8829** [comment]
I didn't verify the PR looks like it broke something, reverting the change
