### ISSUE TITLE
Question of the interpretation of the model output

### ISSUE THREAD

**Issue by johnny-mueller** [zzh8829/yolov3-tf2#264]
In the model.py more precisely in def YoloV3() output_0, output_1 and output_2 are generated. As far as I understand it correctly these are the corresponding feature maps. 
These feature maps have the following dimensions 13 x 13 x 85, 26 x 26 x 85 and 52 x 52 x 85. The first two numbers stand for the grid and the 85 contains the following information 𝑝𝑐,𝑏𝑥,𝑏𝑦,𝑏ℎ,𝑏𝑤 and the remaining 80 numbers stand for the classes.

Now to my question: in which order are the classes of the 80 digits? Is it the same order as in the corresponding coco.names file? So can I assume that the first digit of the eighty digits stands for the class "person" and the second digit for "bicyle" ?

**Comment by zzh8829** [comment]
thats only half correct, you can see the code here 
https://github.com/zzh8829/yolov3-tf2/blob/d63a9921a42dce04cd74ddb529926f9ff81bc41a/yolov3_tf2/models.py#L154

the 85 are bx,by,bw,bh,object follow by 80 classes
in the 80 digits they are indeed same order of names file
