### ISSUE TITLE
training_voc.md - Download Dataset (dead link)

### ISSUE THREAD

**Issue by Loethor** [zzh8829/yolov3-tf2#267]
http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar seems to be dead. So we can't really do:

wget http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar -O ./data/voc2012_raw.tar

is there any other place we can find this file?

**Comment by Harry-KIT** [comment]
you need to install wget.exe

**Comment by Harry-KIT** [comment]
First download wget.exe and put it into System32 file. then try to download by using command on cmd

**Comment by zzh8829** [comment]
you can also just download that link in browser and put it in the location shown

**Comment by MinaGabriel** [comment]
It will take a few seconds for the host to response ... just give it some time
