### ISSUE TITLE
Training on VOC 2012 throws "Incompatible shapes" error

### ISSUE THREAD

**Issue by karthiksprakash** [zzh8829/yolov3-tf2#270]
First of all, amazing work @zzh8829 and all the other contributors. Thank you for putting this together!

I downloaded the VOC 2012 dataset and started training it following the instructions. I see the following error in the **first epoch**:

> InvalidArgumentError: Incompatible shapes: [0,13,13,3] vs. [0]  [Op:Mul]

Here's part of the stack trace: 

`  File "C:\Users\Karthik\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py", line 143, in __call__
    losses = self.call(y_true, y_pred)

  File "C:\Users\Karthik\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py", line 246, in call
    return self.fn(y_true, y_pred, **self._fn_kwargs)

  File "C:\projects\yolov3\models.py", line 305, in yolo_loss
    (1 - obj_mask) * ignore_mask * obj_loss

  File "C:\Users\Karthik\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\math_ops.py", line 984, in binary_op_wrapper
    return func(x, y, name=name)

  File "C:\Users\Karthik\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\math_ops.py", line 1283, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)

  File "C:\Users\Karthik\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\ops\gen_math_ops.py", line 6089, in mul
    _ops.raise_from_not_ok_status(e, name)

  File "C:\Users\Karthik\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [0,13,13,3] vs. [0] [Op:Mul]`

Below are some parameters that I'm training with:

-  --weights_num_classes=80 **(typo corrected)**
- Size = 416. 
- transfer=darknet. 
- Batch size = 4

I've downloaded the latest Yolov3 weights and converted them using the convert.py tool. 

Is there anything that I'm missing? I'm still learning, but It appears that the error is due to unstable weights. Maybe 'no_output' or 'fine_tune' would have better chance?

**Comment by Morgensol** [comment]
> --weights_num_classes=20
Why are you trying to use 20 classses from the weights?
Unless you aren't using the official weights you have to use 80, and it is only necessary to specify this if you are transfer learning

**Comment by karthiksprakash** [comment]
> > --weights_num_classes=20
> 
> Why are you trying to use 20 classses from the weights?
> Unless you aren't using the official weights you have to use 80, and it is only necessary to specify this if you are transfer learning

Sorry, that was a typo. I'm using --weights_num_classes=**80** and --num_classes=**20**

**Comment by karthiksprakash** [comment]
Turns out this is an issue with using 'MirroredStrategy(cross_device_ops=ReductionToOneDevice())'. 

The training works fine on a single GPU. I had to use ReductionToOneDevice for Windows, but the above strategy with default cross_device_ops might work fine on Linux.
