### ISSUE TITLE
Ran out of memory trying to allocate....

### ISSUE THREAD

**Issue by Morgensol** [zzh8829/yolov3-tf2#297]
It seems that the images in the dataset is all loaded into the GPU RAM, which leads to this warning.
With a big enough dataset this will crash the program unless you have enough GPU RAM.

Is there a way smart/easy way of not loading all of the dataset at once into the RAM?

**Comment by liuliuball45** [comment]
You can specify the batch_size to a smaller number when you train the model.

**Comment by zzh8829** [comment]
smaller batch size will help, also you can experiment with disabling set_memory_growth if you are not doing anything else during training
