### ISSUE TITLE
transfer learning example

### ISSUE THREAD

**Issue by amh28** [zzh8829/yolov3-tf2#302]
Hello, 
I have a doubt for creating tfrecord files for training on Pascal VOC. In your tutorial you tell us to run the voc2012.py script but in the code, it reads the list of images from **'aeroplane_' + FLAGS.set + '.txt'**. But why in your transfer learning example do you create train and validation tfrecords from that file if it only contains images specific from aeroplane. Instead I would like to fine-tune on all Pascal classes.

Thanks

**Comment by zzh8829** [comment]
The VOC dataset doesn't have separate image lists for different classes. `*_train.txt` are all the same list.
