### ISSUE TITLE
How to train or predict on rectangle image input?

### ISSUE THREAD

**Issue by makercob** [zzh8829/yolov3-tf2#31]
Most of the images in my dataset are rectangle, with width to height ratio of 16:9. In which way should I modify the function of 'transform_targets_for_output' or other, if training and predicting on rectangle images is desired? Thanks.

**Comment by zzh8829** [comment]
If you are only doing inference you can simply use this https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/resize_with_pad

But for training you also need to resize and pad the bounding box accordingly which is non-trivial.
This is a example on how this might be done https://nbviewer.jupyter.org/github/aleju/imgaug-doc/blob/master/notebooks/B02%20-%20Augment%20Bounding%20Boxes.ipynb

**Comment by makercob** [comment]
Wouldn't resizing or padding images, say 1920×1080 pixels(16:9), to 416×416(or 608×608), introduces loss or distortion of features? Is it possible that some modification could be made to the function of 'transform_targets_for_output' , so that input size of (544, 960, 3) can be accepted?

**Comment by kylemcdonald** [comment]
I had to make a small adjustment to get rectangular input working, see issue #105

**Comment by zzh8829** [comment]
Im gonna use https://github.com/zzh8829/yolov3-tf2/issues/105 to track feature related to custom image resolution
