### ISSUE TITLE
What is predict json data should be like when using tensorflow serving for inferring?

### ISSUE THREAD

**Issue by WorstCodeWay** [zzh8829/yolov3-tf2#314]
Hi, I'm so appreciated your work, it's great for me to learn `Tensorflow` and `Yolo`. And I'm trying to use this model to predict from a Tensorflow Serving service.

Below, I construct a json message and send it to serving but receives nothing and the `tf serving` stays quiet all the time for sure.
Now I'm blocked here.

**Question**
What should the RESTful format for predict on condition of one image? 

**My solution**
```json
{
  "instances": {"b64": "fdsdfsfds42ewvs34232njnkn234n23kj423o4234n2342j42k3n42l3j4o2j34o2oj34l2n34o234kh432k234"},
  "signature_name": "serving_default"
}
```

**Comment by johnny-mueller** [comment]
I think this question is better suited to Stackoverflow. This is only about issues concerning the implementation of @zzh8829 .

**Comment by WorstCodeWay** [comment]
> I think this question is better suited to Stackoverflow. This is only about issues concerning the implementation of @zzh8829 .

You are right. And I figure it out now.
