### ISSUE TITLE
Issue with detect script

### ISSUE THREAD

**Issue by varunvbsci** [zzh8829/yolov3-tf2#32]
I am having trouble running the detect.py script. When I run it after training and loading weights from that training, I get this error:

Traceback (most recent call last):
  File "detect.py", line 65, in <module>
    app.run(main)
  File "C:\Users\venkav1\AppData\Local\Continuum\anaconda3\envs\tf-n\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\venkav1\AppData\Local\Continuum\anaconda3\envs\tf-n\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 53, in main
    for i in range(nums[0]):
TypeError: 'Tensor' object cannot be interpreted as an integer

When I print out nums, it gives this <tf.Tensor 'yolov3/yolo_nms/combined_non_max_suppression/CombinedNonMaxSuppression:3' shape=(1,) dtype=int32>)

Any idea on how to fix this?

**Comment by zzh8829** [comment]
thats weird the output shape of NMS shoudln't be (1,).
does detect.py work with default pretrained weights? how did you train and load weights.

**Comment by varunvbsci** [comment]
It produces the same result and error when i load the pre-trained darknet weights. I trained using the train.py script and loaded the checkpoint file yolov3_train_2.tf that was produced by the training script in this line. 
flags.DEFINE_string('weights', './checkpoints/yolov3_train_2.tf',
                    'path to weights file')

For loading the pretrained weights, I just used the yolov3.tf file that is produced from the convert.py script.

**Comment by Pari-singh** [comment]
I am getting the same error. The nums varaible is a tensorflow varaible and not an integer. I am getting boxes,  scores and everything as 0s from yolov3(img). Any clue why this is happening?

**Comment by Pari-singh** [comment]
I am getting the same error as @varunvbsci, did you figure out the solution to it?

**Comment by zzh8829** [comment]
can you update to the latest version and try again?
