### ISSUE TITLE
Nothing displayed after proper transfer learning with custom dataset

### ISSUE THREAD

**Issue by IAFutur** [zzh8829/yolov3-tf2#322]
Hi all!

I wanted to use the model to get custom detection of guitar on video feed (plz dont ask me why ^^). I built my dataset properly, annotated it with labelimg, converted to suitable xml with the hierarchy similar to the voc2012 one. The training is going on very well, it produces 10 checkpoints along the way. But when I try to detect a guitar on one of the dataset image, it returns nothing...

Could you help on this one or at least provide better explanation for the transfer learning part ? 

Thx in advance :-)

**Comment by WhiteCrow5** [comment]
I ran into a  similar problem. HOPE SOME GUYS CAN HELP US   !!!!!!      ToT!!!

**Comment by innat** [comment]
@IAFutur You may need to tweak the post-processing methods.

**Comment by IAFutur** [comment]
> @IAFutur You may need to tweak the post-processing methods.

@innat yeah well maybe it was the problem. Anyway, this implementation of yolov3 was a little bit old and largely uncommented so I suppose my problem came from a bad comprehension of config files. For one year, I had been struggling with this implementation but now I suggest you to work on yolov4 which is muh more commented on https://alexeyab84.medium.com/yolov4-the-most-accurate-real-time-neural-network-on-ms-coco-dataset-73adfd3602fe. 
Hope it helps 
VA
