### ISSUE TITLE
Comment error

### ISSUE THREAD

**Issue by qiaocheng110** [zzh8829/yolov3-tf2#327]
@zzh8829  
hi author:
i find the comments in  dataset.py ,
" # y_true_out: (N, grid, grid, anchors, [x, y, w, h, obj, class]) " should be changed to  " # y_true_out:(N, grid, grid, anchors, [x1, y1, x2, y2, obj, class])" 
Hope to receive your reply

**Comment by rajan780** [comment]
Hi @qiaocheng110 
Yes, you are correct it seems to be comment mistake, by mistake he wrote # y_true_out: (N, grid, grid, anchors, [x, y, w, h, obj, class]) " 
but in models.py in yolo loss function you saw there he mention correctly in comments # y_true: (batch_size, grid, grid, anchors, (x1, y1, x2, y2, obj, cls))(line no 269)  
https://github.com/zzh8829/yolov3-tf2/blob/master/yolov3_tf2/models.py#L269

**Comment by zzh8829** [comment]
you are absolutely correct, comment fixed in https://github.com/zzh8829/yolov3-tf2/commit/c43df87d8582699aea8e9768b4ebe8d7fe1c6b4c#diff-20e8009f04436ea5ad58a6307c31ce34e2874c410631653e987066c4cb16c592
