### ISSUE TITLE
Inconsistency with comments

### ISSUE THREAD

**Issue by escudero** [zzh8829/yolov3-tf2#333]
Hi,

Studying the **transform_targets_for_output** function of the **dataset.py**, I realized that the comments don't make much sense.
In the comments are as follows:
```python
# y_true_out: (N, grid, grid, anchors, [x, y, w, h, obj, class])
# grid[y][x][anchor] = (tx, ty, bw, bh, obj, class)
```
But I have the impression that the first 4 numbers are 2 coordinates, for example:
`(x1, y1, x2, y2, obj, class)`

To be faithful to the paper, shouldn't it be `(tx, ty, bw, bh, obj, class)`?

Thanks

**Comment by zzh8829** [comment]
I'm pretty sure they are transformed later in model.py loss function, you can double-check on that.
