### ISSUE TITLE
resized image has wrong aspect ratio

### ISSUE THREAD

**Issue by Hugh0120** [zzh8829/yolov3-tf2#36]
It seems in  [https://github.com/zzh8829/yolov3-tf2/blob/eb30bd48ac1354a329a0763b2a8fe57364c5a272/yolov3_tf2/dataset.py](url) you just simply resized original image into shape of (416, 416)

`def transform_images(x_train, size):
    x_train = tf.image.resize(x_train, (size, size))
    x_train = x_train / 255
    return x_train
`

However, I think it might cause image distortion and make anchors meaningless. In darknet, the author use letterbox() method to keep image aspect ratio by padding.

Have you compared the results of different resizing method?

**Comment by zzh8829** [comment]
You are 100% correct on this, I have not compared the result of different resizing methods but theoretically it would reduce accuracy for sure.

I couldn't find good portable implementation of letterbox resize on both images and bounding boxes that why I didn't include them.

**Comment by makercob** [comment]
Majority of my dataset images have aspect ratio of 16:9(1080p). By resizing them to (416,416) with tf.image.resize, training loss did converge. Although, when testing, recall is low, about 50% only.

**Comment by Pari-singh** [comment]
Did you try changing the size from (416, 416) to a higher resolution, maybe (1088, 1088)?

**Comment by Hugh0120** [comment]
Solved this by `tf.image.resize_with_pad`, need to modify the annotations accordingly

**Comment by nickkimer** [comment]
> Solved this by `tf.image.resize_with_pad`, need to modify the annotations accordingly

@Hugh0120 would you mind sharing how you adjusted the annotations through your code to match the resize_with_pad?

**Comment by VeeranjaneyuluToka** [comment]
Anybody changed annotations also when we use tf.image.resize_with_pad?

I am also trying to using tf.image.resize_with_pad but need to adjust bounding boxes also. Try to do that but am not getting image size from tf.image.decode_jpeg api, anybody has solved this issue?

**Comment by VeeranjaneyuluToka** [comment]
Any update on this? I also just did changes so that it uses resize_with_path but not sure how to modify the annotations as tf.image.decode_jpeg does not return valid shape of tensor.

**Comment by LitenPingvin** [comment]
Have anyone have a solution to this issue?
