### ISSUE TITLE
Potential Bug in Ground True Box Encoding

### ISSUE THREAD

**Issue by arielbenitah** [zzh8829/yolov3-tf2#37]
Hi,
You may have a bug in **dataset.py line 36**: 
Instead of the line:  idx, [box[0], box[1], box[2], box[3], 1, y_true[i][j][4]])
I think that it must be
[box[0], box[1], **box[2]-box[0]**, **box[3]-box[1]**, 1, y_true[i][j][4]])

Can you please confirm?

Thanks

**Comment by zzh8829** [comment]
I believe code there is correct.
the subtraction is done here https://github.com/zzh8829/yolov3-tf2/blob/e5130786a33dcc612e2617949616defff34237c0/yolov3_tf2/models.py#L267

**Comment by arielbenitah** [comment]
Hi,
thanks a lot for this quick answer. You're right: it's done in the procedure you point out. 
Thanks a lot!
