### ISSUE TITLE
trouble with `import cv2` when running the demo scripts

### ISSUE THREAD

**Issue by chrisrapson** [zzh8829/yolov3-tf2#39]
When running the commands in your readme, I get an error when I call `python convert.py`:

```
$ python convert.py
Traceback (most recent call last):
  File "convert.py", line 4, in <module>
    from yolov3_tf2.models import YoloV3, YoloV3Tiny
  File "/current/working/directory/models.py", line 21, in <module>
    from .utils import broadcast_iou
  File "/current/working/directory/utils.py", line 4, in <module>
    import cv2
ImportError: /usr/lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates
```

It also seems strange to me that the symbol actually does appear in the libcairo file:
```
$ grep FT_Get_Var_Design_Coordinates /usr/lib/x86_64-linux-gnu/libcairo.so.2
Binary file /usr/lib/x86_64-linux-gnu/libcairo.so.2 matches
```

The error does not originate in your yolov3-tf2 code, but it might be related to the dependencies. Could you please check the versions of the dependency packages you have installed? It might help for me to downgrade some of them.

I am working on Ubuntu 18.04.2 LTS, with python 3.6.0, pip3 version 9.0.1 and conda 4.6.11

Edit: I should add that I am testing this on a computer without a GPU before migrating to one with a GPU. In the meantime, I have substituted the python package `tensorflow-gpu-2.0.0a0` for `tensorflow-2.0.0a0`

Edit: after some additional investigation, I suspect I have somehow messed up a combination of things installed with `apt`, `pip3`, `python3 -m pip` and `conda`. It might be helpful if you could share the output of your `python3 -m pip freeze` and `conda list` for a working installation. Then I can compare it with my system.

**Comment by zzh8829** [comment]
I just did a clean install on ubuntu 18.04 using anaconda without any problem.
I recommend you redo everything with conda.
all I did was `conda env create -f environment.yml`
make sure you are using conda python and not system python or pip

**Comment by chrisrapson** [comment]
thanks, I think system pip might have been involved. Anyway, I cleaned out my python installation and this time everything worked :-) so definitely all my fault. Sorry about the false alarm.

Great work, by the way!
