### ISSUE TITLE
export inference graph

### ISSUE THREAD

**Issue by sonfiree** [zzh8829/yolov3-tf2#4]
How to implement export_inference_graph?
Go to tensotflow serving

**Comment by zzh8829** [comment]
I did some experimentation, looks like export to tensorflow serving is broken for layers with multiple outputs. I will implement it here once the the issues in tensorflow repo gets resolved 
https://github.com/tensorflow/tensorflow/issues/28066

**Comment by zzh8829** [comment]
In the meantime, I made it work with some hack. see example at https://github.com/zzh8829/yolov3-tf2/blob/master/export_tfserving.py and some instructions in the readme file
