### ISSUE TITLE
Cannot train at all: AttributeError: 'Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by schneider128k** [zzh8829/yolov3-tf2#40]
Detection works without any problems. When try running the first command as explained in README under training (applied to my train and test sets), I get the following error message. 

(yolov3-tf2-master) C:\Users\Pawel Wocjan\Documents\ML\yolov3-tf2-master>python train.py --batch_size 8 --dataset "C:\Users\Pawel Wocjan\Documents\ML\yolov3-tf2-master\data\racoon_dataset\train.record" --val_dataset "C:\Users\Pawel Wocjan\Documents\ML\yolov3-tf2-master\data\
racoon_dataset\test.record" --epochs 100 --mode eager_tf --transfer fine_tune
W0724 12:49:11.198809  5172 deprecation.py:506] From C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated an
d will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-07-24 12:49:13.840923: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
W0724 12:49:14.279574  5172 deprecation.py:323] From C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\tensorflow\python\autograph\impl\api.py:255: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated an
d will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    app.run(main)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Pawel Wocjan\Documents\ML\Environments\yolov3-tf2-master\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 129, in main
    epoch, batch, total_loss.numpy(),
AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by schneider128k** [comment]
I am using tensorflow-gpu==2.0.0-alpha2. I printed out the value produced by tf.executing_eagerly() in at the beginning of main and saw that it False. After adding tf.enable_eager_execution() in main, I could start training (but run into some other issue later on).

**Comment by zzh8829** [comment]
interesting, i thought tensorflow 2.0 default to executing eagerly, did you disable it somehow

**Comment by schneider128k** [comment]
Yes, you are right. I installed everything from scratch (tensorflow-gpu etc.) again and everything works now.
