### ISSUE TITLE
Accurary implementation?

### ISSUE THREAD

**Issue by ilyes-hamrouni** [zzh8829/yolov3-tf2#46]
Is there anyone who added some accuracy to the detection or training?

**Comment by DeltaTesting** [comment]
I've done so on a custom detection script that i use to choose the checkpoint with better results on my validation dataset. I won't share the code since is very specyfic for my dataset, but the pseudo code would be:


> for checkpoint in checkpoints:
> -model.load_weights(checkpoint)
> -for img, labels in val_dataset:
> --boxes, scores, classes, nums = model.predict(img)
> --labels2 = labels.copy()
> --acc = 0
> --for i in range(nums[0]):
> ---box = boxes[0][i]
> ---c = classes[0][i]
> ---for l in labels2:
> ----gt_box = getBox(l)
> ----if boxesIntersect(box, gtbox) and sameClass(c, l):
> -----acc += 1
> -----labels2.remove(l)
> -----break
> --accuracy = acc / len(labels)

**Comment by zzh8829** [comment]
merging with https://github.com/zzh8829/yolov3-tf2/issues/125

**Comment by ethanyanjiali** [comment]
@DeltaTesting it seems like in your code, one detection (predicted box) would just match the first ground truth box that satisfy the iou and class condition. so if that particular ground truth box is better to be matched with another detection, there would be a miss here. Does your dataset mostly just contains one bounding box, or are those ground truth boxes usually not close with each other?
