### ISSUE TITLE
Threshold option during detection

### ISSUE THREAD

**Issue by SlavaKeshkov** [zzh8829/yolov3-tf2#49]
Hey @zzh8829, thanks for your code, works great. I was thinking it would be a good idea to have a detection threshold flag --thresh for the `detection.py` or `conversion.py`. Do I get it right that `iou_threshold` and `score_threshold `in lines `190-192` of `models.py ` is the only way to change threshold for prediction? Let me know, this flag along with num_classes flag would be a great boost to the repo.

**Comment by zzh8829** [comment]
done
