### ISSUE TITLE
inference speed question

### ISSUE THREAD

**Issue by yuntai** [zzh8829/yolov3-tf2#50]
Thanks for a very clean implementation! I'm getting 0.6 sec for `predict()` on 1080ti and puzzled why this should be so slow. With a similar implementation, I am able to get > 30 fps. 
Any idea, please?

**Comment by zzh8829** [comment]
are you using tensorflow gpu? you can check using nvidia-smi

**Comment by yuntai** [comment]
I think I had a problem with my custom-built tf2.0-gpu. With official tf2-gpu, it is faster( ~25 fps. found `predict_on_batch` is at least ~30% faster!?). Still slow than other implementations I tried but didn't investigate further. Thanks for clean implementation, again!
