### ISSUE TITLE
Metrics : how to track the model? 

### ISSUE THREAD

**Issue by remic33** [zzh8829/yolov3-tf2#55]
Hello, i wanted to know how do you track that model accuracy ?
I only see loss tracking, i wonder if it is possible to follow an accuracy on validation dataset?

**Comment by AnaRhisT94** [comment]
@remic33  Have you managed to track the loss values? I'm getting `nan`s.

**Comment by remic33** [comment]
Hello ! If you get nans there is a problem in your code, usually it is a number of class problem. 
To get accuracy of my model, I know use https://github.com/rafaelpadilla/Object-Detection-Metrics

**Comment by AnaRhisT94** [comment]
@remic33  Thanks for your comment. I'm using `2` classes. also in my `coco.names` I have just 2 classes.
I also tried with the original Darknet weights which have `80` classes, and it's corresponding `coco.names`, but it didn't train either.

**Comment by zzh8829** [comment]
merge to https://github.com/zzh8829/yolov3-tf2/issues/125
