### ISSUE TITLE
Paddings must be non-negative error while training Yolo-Tiny

### ISSUE THREAD

**Issue by aniketmaurya** [zzh8829/yolov3-tf2#56]
I am using widerface dataset for training Yolo-Tiny model. 
> python train.py --batch_size 32 --dataset ./data/train.record --epochs 10 --mode eager_tf --transfer fine_tune --weights ./checkpoints/yolov3-tiny.tf --tiny

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/content/drive/My Drive/yolov3-tf2/train.py in <module>()
    178 if __name__ == '__main__':
    179     try:
--> 180         app.run(main)
    181     except SystemExit:
    182         pass

7 frames
/usr/local/lib/python3.6/dist-packages/absl/app.py in run(main, argv, flags_parser)
    298       callback()
    299     try:
--> 300       _run_main(main, args)
    301     except UsageError as error:
    302       usage(shorthelp=True, detailed_error=error, exitcode=error.exitcode)

/usr/local/lib/python3.6/dist-packages/absl/app.py in _run_main(main, argv)
    249     sys.exit(retval)
    250   else:
--> 251     sys.exit(main(argv))
    252 
    253 

/content/drive/My Drive/yolov3-tf2/train.py in main(_argv)
    118 
    119         for epoch in range(1, FLAGS.epochs + 1):
--> 120             for batch, (images, labels) in enumerate(train_dataset):
    121                 with tf.GradientTape() as tape:
    122                     outputs = model(images, training=True)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py in __next__(self)
    620 
    621   def __next__(self):  # For Python 3 compatibility
--> 622     return self.next()
    623 
    624   def _next_internal(self):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py in next(self)
    664     """Returns a nested structure of `Tensor`s containing the next element."""
    665     try:
--> 666       return self._next_internal()
    667     except errors.OutOfRangeError:
    668       raise StopIteration

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py in _next_internal(self)
    649             self._iterator_resource,
    650             output_types=self._flat_output_types,
--> 651             output_shapes=self._flat_output_shapes)
    652 
    653       try:

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_dataset_ops.py in iterator_get_next_sync(iterator, output_types, output_shapes, name)
   2671       else:
   2672         message = e.message
-> 2673       _six.raise_from(_core._status_to_exception(e.code, message), None)
   2674   # Add nodes to the TensorFlow graph.
   2675   if not isinstance(output_types, (list, tuple)):

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: {{function_node __inference_Dataset_map_<lambda>_2432}} Paddings must be non-negative: 0 -19
	 [[{{node Pad}}]] [Op:IteratorGetNextSync]
```

**Comment by aniketmaurya** [comment]
The problem was with my dataset.

**Comment by DeltaTesting** [comment]
Which problem did you find in your dataset? i'm facing a very similar problem.

**Comment by tekotan** [comment]
Yes I am having the same issue. Can you please explain what you did to fix your dataset?

**Comment by Yeah-Kun** [comment]
when I execute the command 
`python train.py --batch_size 4 --dataset ./data/train.record --epochs 8 --mode eager_tf --transfer fine_tune --weights./checkpoints/yolov3-tiny.tf --tiny`
I got this (ValueError), It seems like shape was wrong, how can I fix this problem?
`Traceback (most recent call last):
  File "d:\github repo\yolov3-tf2\train.py", line 211, in <module>
    app.run(main)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "d:\github repo\yolov3-tf2\train.py", line 86, in main
    model.load_weights(FLAGS.weights)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1149, in load_weights
    status = self._trackable_saver.restore(filepath)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 1270, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 908, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 289, in restore_saveables
    validated_saveables).restore(self.save_path_tensor)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\saving\functional_saver.py", line 255, in restore
    restore_ops.update(saver.restore(file_prefix))
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\saving\functional_saver.py", line 102, in restore
    restored_tensors, restored_shapes=None)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\training\saving\saveable_object_util.py", line 115, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 291, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "C:\Users\BZL\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py", line 1115, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (18,) and (255,) are incompatible
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-6
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-7
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-7
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-8
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6.arguments
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-6.arguments
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6._variable_dict
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-6._variable_dict
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6._trainable_weights
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-6._trainable_weights
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-6._non_trainable_weights
W1106 16:06:23.211744 27176 util.py:144] Unresolved object in checkpoint: (root).layer-6._non_trainable_weights
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-7.arguments
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-7.arguments
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-7._variable_dict
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-7._variable_dict
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-7._trainable_weights
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-7._trainable_weights
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-7._non_trainable_weights
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-7._non_trainable_weights
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8.arguments
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-8.arguments
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8._variable_dict
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-8._variable_dict
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8._trainable_weights
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-8._trainable_weights
WARNING:tensorflow:Unresolved object in checkpoint: (root).layer-8._non_trainable_weights
W1106 16:06:23.212740 27176 util.py:144] Unresolved object in checkpoint: (root).layer-8._non_trainable_weights
WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
W1106 16:06:23.212740 27176 util.py:152] A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
`

**Comment by nickkimer** [comment]
> The problem was with my dataset.

@aniketmaurya what was the problem with your dataset?

**Comment by aniketmaurya** [comment]
When I tried to parse my train.record, some of the image failed to load. So I deleted those images and then it worked.

**Comment by aniketmaurya** [comment]
Also this error comes when your image size is too low.
