### ISSUE TITLE
detect.py with own weights

### ISSUE THREAD

**Issue by remic33** [zzh8829/yolov3-tf2#57]
After training my model with no transfert, I want to try it and see if it work using detect.py
In the checkpoints folder for every epoch I have two file : 
- yolov3_train_EPOCHNUM.tf.index
- yolov3_train_EPOCHNUM.tf.data-00000-of-00001
I tried to use 
`python detect.py --image /path/to/img.jpg --weights yolov3_train_EPOCHNUM.tf 
`I get a shape error.
`python detect.py  --image /path/to/img.jpg --weights yolov3_train_EPOCHNUM.tf.index 
`And get a huge numpy array but no output
`python detect.py  --image /path/to/img.jpg --weights yolov3_train_EPOCHNUM.tf.data-00000-of-00001 `
and get : OSError: Unable to open file (file signature not found)

How am I supposed to use those checkpoints?

**Comment by htzmedia** [comment]
Did you check the Flags? Resolution, number of classes...

python detect.py --image test.jpg --weights ./checkpoints/yolov3_train_EPOCHNUM.tf --num_classes 15 --size 416 --classes custom.names --tiny False

Something like this should work.

**Comment by remic33** [comment]
it dont : 
Two checkpoint references resolved to different objects (<yolov3_tf2.batch_norm.BatchNormalization object at 0x7fd03418a710> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fd0341b3400>).
[Dimension(3), Dimension(3), Dimension(3), Dimension(16)]

**Comment by remic33** [comment]
Ok I just found that my detect.py give me a FLAGS.tiny = True even if it's false.

**Comment by finaldzn** [comment]
Hello @remic33 how did you fix your issue ? I tried hard coding the FLAGS.tiny = False but i still run into the shape error

**Comment by remic33** [comment]
Hello @finaldzn !
First I printed inside my function FLAGS.tiny to see if it was really the problem, 
When It showed me that it was it, I just deleted it and made yolov3 run by default.

**Comment by finaldzn** [comment]
@remic33  thanks for the quick answer, unfortunally my issue wasn't fix by that i suspect its not the same thing causing the error.
Thanks anyway
