### ISSUE TITLE
transform_targets与YoloOutput

### ISSUE THREAD

**Issue by 1044197988** [zzh8829/yolov3-tf2#58]
transform_targets的输出是什么？
(
  [N, 13, 13, 3, 6],
  [N, 26, 26, 3, 6],
  [N, 52, 52, 3, 6]
)
其中N是批处理中的标签数，最后一个尺寸“6”表示 [x, y, w, h, obj, class]边界框。

但是
def YoloOutput(filters, anchors, classes, name=None):
    def yolo_output(x_in):
        x = inputs = Input(x_in.shape[1:])
        x = DarknetConv(x, filters * 2, 3)
        x = DarknetConv(x, anchors * (classes + 5), 1, batch_norm=False)
        x = Lambda(lambda x: tf.reshape(x, (-1, tf.shape(x)[1], tf.shape(x)[2],
                                            anchors, classes + 5)))(x)
        return tf.keras.Model(inputs, x, name=name)(x_in)
    return yolo_output
x最后一维为5+classes
如果classes为20
那么 
(
  [N, 13, 13, 3, 25],
  [N, 26, 26, 3, 25],
  [N, 52, 52, 3, 25]
)
这与transform_targets的并不符合啊
但是我看到loss的计算用到了sparse_categorical_crossentropy
所以我认为transform_targets的形状是对的

但是如果训练新的数据集的话，需要做什么修改吗？
还是transform_targets后直接送入模型训练

**Comment by zzh8829** [comment]
target_transforms 输出的 class 是 categorical, yolo_output 是 onehot
新的数据集用这个各式就行
https://github.com/zzh8829/yolov3-tf2/blob/master/yolov3_tf2/dataset.py#L79
