### ISSUE TITLE
Limit GPU Usage 

### ISSUE THREAD

**Issue by ozangungortuhh** [zzh8829/yolov3-tf2#59]
I would like to limit the GPU usage of the tensorflow model that I am using but when I add these 2 lines to my script:

```
 tf.config.gpu.set_per_process_memory_fraction(0.75)
 tf.config.gpu.set_per_process_memory_growth(True)
```

I get the following error:
AttributeError: module 'tensorflow._api.v2.config' has no attribute 'gpu'

I installed `pip install tensorflow-gpu==2.0.0-rc0` and can see it on pip list. 
Is there anything else I should install to be able to limit gpu usage?

Thanks in advance

**Comment by fnando1995** [comment]
Hello @ozangungortuhh i wanna do the same. Any results yet?

**Comment by zzh8829** [comment]
Here is the new API for gpu settings,
since these are still experimental I didn't implement them here
https://www.tensorflow.org/beta/guide/using_gpu#limiting_gpu_memory_growth

**Comment by ozangungortuhh** [comment]
The solution above worked for me @fnando1995. Thanks @zzh8829
