### ISSUE TITLE
Using all GPU memorry

### ISSUE THREAD

**Issue by fnando1995** [zzh8829/yolov3-tf2#62]
Hello, i´m using this implementation to test it in some videos to learn more. But i have seen it consume all the GPU memory even in if it is only been used for inference. i had checked some stacks and says is default tensorflow behaviour. and it can be configured at:

```
config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)
```

but cant find something like it in the code.

Any help?

kind regards.

**Comment by htzmedia** [comment]
There are no Sessions anymore in TF2.0.

**Comment by DeltaTesting** [comment]
@fnando1995 As you can see [here](https://www.tensorflow.org/beta/guide/using_gpu#limiting_gpu_memory_growth) you can also limit the gpu memory allocation in tf2.

**Comment by fnando1995** [comment]
Thanks! @DeltaTesting Ill be testing it soon.
