### ISSUE TITLE
TypeError when iterating over 'N' in dataset.transform_targets_for_output

### ISSUE THREAD

**Issue by nivsmall** [zzh8829/yolov3-tf2#67]
I'm having trouble training with my own data set. Running train.py script (with a tiny bit of modification for class_num==5 in relevant scripts)
I'm getting this output:
***
"...\yolov3-tf2-master\yolov3_tf2\dataset.py:18 transform_targets_for_output
        for i in tf.range(N):
    Anaconda3\envs\yolov3-tf2\lib\site-packages\tensorflow\python\framework\ops.py:477 __iter__
        "Tensor objects are only iterable when eager execution is

    TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn."
***
When Debugging- N value is unknown, marked as: '?'
I initially thought this was because my TFRecords file were generated differently, but following the code from research.G3doc.using_your_own_data it gives the same error.
***
Prior to that i'm getting a bunch of these Warnings printed out:
"WARNING:tensorflow:Entity <bound method BatchNormalization.call of <yolov3_tf2.batch_norm.BatchNormalization object at 0x000001ED2EB15978>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <yolov3_tf2.batch_norm.BatchNormalization object at 0x000001ED2EB15978>>: AssertionError: Bad argument number for Name: 3, expecting 4
W0915 14:51:04.872189  8468 ag_logging.py:145] Entity <bound method BatchNormalization.call of <yolov3_tf2.batch_norm.BatchNormalization object at 0x000001ED2EB15978>> could not be transformed"
***

using tf.map_fn doesn't solve this either...

**Comment by hasslercastro** [comment]
Did you manage to solve it?

**Comment by hasslercastro** [comment]
@nivsmall Did you manage to solve it?

**Comment by hasslercastro** [comment]
pip install gast==0.2.2 solved the issue

**Comment by nivsmall** [comment]
Well after a couple of debugging days and a lot less hair i realised that even though TF2 was installed it wasn't the one being initialised when importing tensorflow, but rather an older version that does not run 'eagerly' (and obviously could not iterate over the tensor - N)

after rebuilding properly this error doesn't come up :)
I did see elswhere that gast - version is a bug fix for this type of bug so thanx for the heads up
