### ISSUE TITLE
Training problem with .tfrecord files from VoTT

### ISSUE THREAD

**Issue by Maarcusj** [zzh8829/yolov3-tf2#73]
I use tensorflow 2.0.0-beta1

I have problem with training with own training data generated in VoTT and exported as .tfrecord files, every image is generated as a separate tfrecord file. As I understand train.py is only made for one .tfrecord, how to change this for multiple tfrecords?

**Comment by cole8888** [comment]
Did you solve this? I am also having the same issue.

**Comment by Maarcusj** [comment]
Maybe I should not closed the issue, but I had multiple problems with training so I changed implementation to darknet instead.

**Comment by zzh8829** [comment]
it does actually work with multiple tfrecords, you only need to pass in wild card argument like this "data/*.tfrecords"
