### ISSUE TITLE
Running validation on MS-COCO

### ISSUE THREAD

**Issue by p3jawors** [zzh8829/yolov3-tf2#76]
Hi, do you have any examples of running through the validation on batches of images? I am looking at running the network through the MS-COCO validation set to get the mAP scores. Any suggestions are greatly appreciated.

Cheers

**Comment by AnaRhisT94** [comment]
@p3jawors  Were you able to train the network? I'm getting `nan`s all the time.

**Comment by guantinglin** [comment]
I'm also looking for that!

**Comment by zzh8829** [comment]
merging with https://github.com/zzh8829/yolov3-tf2/issues/125
