### ISSUE TITLE
Question on eager execution with SavedModel

### ISSUE THREAD

**Issue by SlavaKeshkov** [zzh8829/yolov3-tf2#77]
Hello @zzh8829,

I have been able to successfully convert a yolo-tiny-v3 model to checkpoints and later on to the SavedModel format for serving. I have a question about how to perform inference in the best way. I see that in your script export_tfserving.py line 60-61 and 72 you use the following notation: 

```
    model = tf.saved_model.load(FLAGS.output)
    infer = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    outputs = infer(img)

```

I tried using your approach in a python script and I notice that it performs fast on 1 image, but slows down considerably on batch sizes of 16, 32, 64 images.  I am wondering - does it have to do with eager execution?

When using Tensorflow 1.14 notation with frozen .pb graphs in a session of similar models, running 1 image is slow but running a batch of images is much faster, especially when using GPU acceleration. This is an old-school way of running it:

```
    input_operation = graph.get_operation_by_name(input_name)
    output_operation = graph.get_operation_by_name(output_name)

    with tf.compat.v1.Session(graph=graph) as sess:
        results = sess.run(
            output_operation.outputs[0],
            {input_operation.outputs[0]: img})

        sess.close()

```
Could you please enlighten me if there is a way to run SavedModel in a session as well, to get faster speed on batches of images? Or, in general, what are the options here?

**Comment by zzh8829** [comment]
In general session don't exist in tf2 anymore. You can check out tensorflow serving i have had good experience with it. Other than that, I recommend `predict_on_batch` function from tf.keras
