### ISSUE TITLE
Max confidence score = 0.5

### ISSUE THREAD

**Issue by remic33** [zzh8829/yolov3-tf2#78]
Hello !
Im currently running that model with one objet detection and 
yolo_iou_threshold =0.1
yolo_iou_threshold=0.1
My maximum score confidence seems to be 0.5 (it is sometimes  exactly 0.5)
I do not  get why... Did someone ever experienced the same issue? Any idea?

**Comment by makercob** [comment]
same here. Perhaps class loss should be discarded?

**Comment by AntiDoctor** [comment]
Yeah I have exactly the same issue, not sure why

**Comment by zzh8829** [comment]
you need to specify  `yolo_score_threshold` for score

**Comment by k-maheshkumar** [comment]
Yeah even i face same problem. I have even unfreezed all layers and trained with one class. I always get max confidence value 0.49(approx). So, I had to reduce yolo_score_threshold = 0.45, for detecting objects in an image.

Am I missing something?. Could you tell me, how can increase the confidence value?

**Comment by WillBnO** [comment]
I honestly tried specifying yolo_score_threshold when training and it didn't seem to make a difference for me, in the end I just left it as it was.
