### ISSUE TITLE
How to detect in parallel

### ISSUE THREAD

**Issue by l976308589** [zzh8829/yolov3-tf2#89]
I use from concurrent.futures import ThreadPoolExecutor as Exe.
then
class ObjectTrack:
    def __init__(self):
        self.config = Config.config['root']

    def __load_picture(self, image):
        img = tf.image.decode_image(image, channels=3)
        img = tf.expand_dims(img, 0)
        return transform_images(img, self.config['size'])

    def decode_pictures(self):
        # 本地测试，正常使用socket
        import json
        with open('Data/SeriImageArray.json', 'rb') as f:
            res = json.load(f)
        pars = [[bytes(image['Image']), res['batch'], True] for image in res['Imagelist']]
        for par in pars:
            self.wrap_decode_picture(par)
        with Exe(4) as Pool:
            Pool.map(self.wrap_decode_picture, pars)

    def wrap_decode_picture(self, pars):
        self.decode_picture(*pars)

    def decode_picture(self, image=bytes(), batch=1, accurate=False):
        model = Model.model_accurate.copy()
        image = self.__load_picture(image)
        boxes, scores, classes, nums = model(image)
        res = [[np.array(scores[0][i]), np.array(boxes[0][i])] for i in range(nums[0]) if int(classes[0][i]) == 0]

        json_str = {"batch": batch,
                    'time': time(),
                    "code": "00001",
                    "target_info": []
                    }
        for score, box in res:
            json_str["target_info"].append(
                {'box': box.tolist(),
                 "player": 1,
                 "person": 1,
                 "socre": float(score)}
            )
        print(json_str)
but nothing happened.Maybe it's because the model can't be serialized
What are the methods of parallel recognition？
thanks

**Comment by zzh8829** [comment]
i would recommend using tensorflow serving for multi threaded inference.
I don't think tensorflow is easy to setup in multithreaded mode

**Comment by l976308589** [comment]
Thank you very much. 
How to identify pictures in batches? 
How should it be modified?

**Comment by zzh8829** [comment]
instead of threadpool you should use keras `predict_on_batch`. Tensorflow is already multithreaded internally, there is no need to run multiple model in parallel
