### ISSUE TITLE
who can prompt any code about how to create the tf-record dataset?

### ISSUE THREAD

**Issue by angryhen** [zzh8829/yolov3-tf2#93]

**Comment by lazerliu** [comment]
I create the tfrecord file(the official pascal voc2007 dataset) with tf-object-detection api script,but it seems something wrong,as the model I trained with the tf-record file can't detect anything!

**Comment by lazerliu** [comment]
If you got one useful script, shall I got one copy?thks!

**Comment by zzh8829** [comment]
https://github.com/zzh8829/yolov3-tf2/blob/master/docs/training_voc.md
