### ISSUE TITLE
how to predict on batch?

### ISSUE THREAD

**Issue by l976308589** [zzh8829/yolov3-tf2#95]
pars is a list.I want to predict on batch so that it will faster.
----------------1---------------
'''
        for par in pars:
            model.predict(par)
  
'''

this is work

--------------2--------------
'''
input_queue = tf.data.Dataset.from_tensor_slices(pars).batch(10)
model.predict(input_queue)
'''

ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (10, 1, 1, 416, 416, 3)
this is not work

--------------3--------------
'''
input_queue = tf.data.Dataset.from_tensor_slices(pars).batch(10)
model.predict_on_batch(input_queue)
'''

ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (10, 1, 1, 416, 416, 3)
this is not work

--------------4--------------
'''
input_queue = tf.data.Dataset.from_tensor_slices(pars).batch(10)
model.predict_generator(input_queue, workers=4, use_multiprocessing=True)
'''

ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (10, 1, 1, 416, 416, 3)
this is not work

what should I do?

**Comment by zzh8829** [comment]
you want to reshape the array to (10, 416, 416, 3) by removing the extra (1,1) dimension
