### ISSUE TITLE
[Benchmark] Speed on RTX 2070 - 100ms?

### ISSUE THREAD

**Issue by AnaRhisT94** [zzh8829/yolov3-tf2#97]
**(Solution in the comments)**
When checking the speed of my RTX 2070 card with this code:
```
        t1 = time.time()
        boxes, scores, classes, nums = yolo(img)
        t2 = time.time()
        print("Inference time on image: {} is {}".format(t2 - t1))
```

I'm getting `100-110ms` speed per an image, on **YoloV3 (416x416) images.**

In the README file the creator of this repo(@zzh8829 ) has stated that he got with a worse graphics card ( GTX 970), speed of `74ms` per an image.

Any ideas why this happens? Anyone had done benchmarking on `detect.py` and willing to share their results? Highly appreciated.

**Comment by antongisli** [comment]
hi! I have been getting about 55ms on my RTX 2080. Which platform are you running on?

**Comment by AnaRhisT94** [comment]
> hi! I have been getting about 55ms on my RTX 2080 with 720p. Which platform are you running on?

@antongisli  Hi Anton,
I'm using Ubuntu 18.04, also tried with nvidia-docker.

**Comment by smalldroid** [comment]
Hi. I cant convert yolov3 weight to yolov3.tf. How to fix it please? My Pc is win 10 and GPU RTX2080ti. 
![ảnh](https://user-images.githubusercontent.com/237886/68677060-ee042c80-058d-11ea-9205-c1ab8dd75922.png)

**Comment by AnaRhisT94** [comment]
> Hi. I cant convert yolov3 weight to yolov3.tf. How to fix it please? My Pc is win 10 and GPU RTX2080ti. Only get yolov3.tf.index.
> ![ảnh](https://user-images.githubusercontent.com/237886/68677060-ee042c80-058d-11ea-9205-c1ab8dd75922.png)

Hi, @smalldroid .
This isn't the thread for this, please open a new one.
Also, it did convert successfully. Your when are located in the folder `checkpoints` and are called `yolov3.tf`, use the `detect.py` to test that out.

**Comment by zzh8829** [comment]
detect.py is not optimized for inference speed. you should check how detect_video is implemented for faster performance

**Comment by AnaRhisT94** [comment]
> detect.py is not optimized for inference speed. you should check how detect_video is implemented for faster performance

Thank you.
The solution is using `yolo.predict(img)` instead of `yolo(img)`.

**Comment by zzh8829** [comment]
thats great to know, the reason is `predict` and `predict_on_batch` create an optimized graph before inference where `yolo(img)` does not. i will update readme with your numbers.

**Comment by IbrahimBond** [comment]
i get like 150ms for yolov3 on an rtx 2080 even though i am using video-detect with predict_on_batch()
what could be the issue?
