### ISSUE TITLE
Use binary crossentroy in case of 2 classes

### ISSUE THREAD

**Issue by aurelienLevecqYouConscious** [zzh8829/yolov3-tf2#99]
Thank you very much for your implementation

I am using your code on my own data set which has 2 classes.
Therefore I would like to use the binary_crossentropy activation.

It is for me a struggle to change the parameters of the functions.

Are you going to implement this ? Or if some one could explain it ?

Thank you in advance and great job thank you

**Comment by AnaRhisT94** [comment]
This repo. works perfectly for 2 classes (and any other number of classes), you don't need to do any changes in order to receive high accuracy results and high speed.

**Comment by zzh8829** [comment]
Exactly, binary_crossentropy is a special case of categorical cross entropy, there is no difference in the actual math behind it.
